config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
     resources :ibans do
       collection {post :import}
     end
  root :to => 'ibans#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/iban.rb
require 'csv'

class Iban < ApplicationRecord

  validates :code, presence: true, uniqueness: true
  def self.import(file)
    if (file != nil)
    CSV.foreach(file.path, headers: false) do |row|
      s_hash = Iban.new
      s_hash.code= row[0]
        if (s_hash.code.match(/^(?=.{1,20}$)[A-Z]{2}\d{2} ?\d{4} ?\d{4} ?\d{4} ?\d{4}/)) && (s_hash.code.include?('7044'))
          s_hash.bank = true
          s_hash.is_seb = 'SEB'
          s_hash.save
        elsif
        (s_hash.code.match(/^(?=.{1,20}$)[A-Z]{2}\d{2} ?\d{4} ?\d{4} ?\d{4} ?\d{4}/)) && (s_hash.code.exclude?('7044'))
          s_hash.bank = true
          s_hash.is_seb = 'BANK'
          s_hash.save
        else
          s_hash.bank = false
          s_hash.is_seb = "Incorrect IBAN"
          s_hash.save
        end
    end
    else

    end
    end


  def self.to_csv
    attributes = %w{code is_seb bank}
    CSV.generate(headers: true) do |csv|
      csv << attributes

      Iban.all.each do |iban|
        csv << [iban.code, iban.is_seb, iban.bank]
      end
    end
  end

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ibans_controller.rb
class IbansController < ApplicationController
  before_action :set_iban, only: [:show, :edit, :update, :destroy]

  def index
    @iban = Iban.all
    @ibans = Iban.where(code: params[:query])
    respond_to do |format|
      format.html
    format.csv { send_data @iban.to_csv }
    end
    end

  def new
    @iban = Iban.new
  end

  def import
    if params[:file].nil?
    redirect_to :action => 'new', alert: "CSV document not present."
      else
    @ibans = Iban.all
    Iban.import(params[:file])
    redirect_to :action => 'index'
    end
  end

  def self.to_csv
    attributes = %w{code is_seb bank}
    CSV.generate(headers: true) do |csv|
      csv << attributes

      @iban.each do |iban|
        csv << [iban.code, iban.is_seb, iban.bank]
      end
    end
  end

  private

  def set_iban
    @iban = Iban.find(params[:id])
  end

  def iban_params
    params.require(:iban).permit(:code, :bank, :is_seb)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ibans_helper.rb
module IbansHelper
end

app/views/ibans/index.html.erb
<p id="notice"><%= notice %></p>
<div id="header02" class="clear" style="background-image: url(https://www.seb.lt/sites/default/files/web/backgrounds/bg_green_dark.jpg);">
<h1>Iban verification</h1>
</div>
<div class="box">

<%= form_tag ibans_path, method: :get do %>
  <%= text_field_tag :query,
                      params[:query],
                      placeholder: "Find IBAN"
  %>
    <input type="submit" id="edit-submit" name="op" value="Find" class="form-submit">
<% end %>

<table >

  <tbody>
  <% @ibans.each do |iban| %>
    <tr>
    <td><h5>Found examples</h5></td>
      <td><%= iban.code %></td>
      <td class="btn btn-light"><%= link_to 'Show more information', iban %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

</div>

<div class="btn btn-light">
  <%= link_to 'Download CSV list', ibans_path(format: :csv), :class => "btn" %> |
  <%= link_to 'Add Data from CSV', new_iban_path, :class => "btn"%>

</div>

app/views/ibans/new.html.erb
<div id="header02" class="clear" style="background-image: url(https://www.seb.lt/sites/default/files/web/backgrounds/bg_green_dark.jpg);">

<%= form_tag import_ibans_path, :class => 'form-inline',multipart: true do  %>
  <%= file_field_tag :file %>
    <%= button_tag(type: "Import selected data to database", class: "btn btn-default") do %>
      <h10>Add data to database</h10>
    <% end %>
    <% end %>


</div>
<div class="btn btn-light" >
  <%= link_to 'Back', ibans_path,:class => "btn"%>
</div>

app/views/ibans/show.html.erb
<p id="notice"><%= notice %></p>

<div class="alert alert-success" role="alert">
<p>
  <strong>Code:</strong>
  <%= @iban.code %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @iban.bank %>
</p>

<p>
  <strong>Is seb:</strong>
  <%= @iban.is_seb %>
</p>
</div>
<div class="btn btn-light" >
<%= link_to 'Back', ibans_path,:class => "btn"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IbanTikrinimas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'ibans.css' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>